logging:
    level:
#        tk.mybatis: DEBUG
        com.bwzcpt.security.crm: DEBUG
server:
    port: 9808

spring:
    application:
        name: ace-activiti
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: activiti
        url: jdbc:mysql://${MYSQL_HOST:rm-2ze44680d6g4xsfg4.mysql.rds.aliyuncs.com}:${MYSQL_PORT:3306}/activiti?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
        username: bw_zhywxt
        password: Bw_1qaz2wsx
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    mvc:
      view:
        prefix: /WEB-INF/pages/
        suffix: .jsp
    redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.103}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
        addresses: ${RABBIT_MQ_HOST:10.99.10.103:5672}
        username: rabbitadmin
        password: 123456
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.bwzcpt.security.crm
    title: ace-activiti
    version: 1.0.0.SNAPSHOT
    description: 业务服务
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-activiti
    secret: 123456
    token-header: client-token

mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper