server:
  port: 9091
#debug: true

spring:
  application:
    name: ace-activiti
  jackson:
          date-format: yyyy-MM-dd HH:mm:ss
          time-zone: GMT+8
          default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:rm-2ze49f7ouzmbv7y01.mysql.rds.aliyuncs.com}:${MYSQL_PORT:3306}/activiti?characterEncoding=utf8&amp;serverTimezone=UTC&useSSL=false&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: bw_zhywxt
    password: Bw_1qaz2wsx
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
   redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.103}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
   cloud:
        inetutils:
            preferred-networks: ${NETWORKS_WD:10.255.0}

#热部署
# devtools:
#   restart:
#     enabled: true
#     trigger-file: devtools.tg


#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

