logging:
    level:
#        tk.mybatis: DEBUG
        com.bwzcpt.security.crm: DEBUG
server:
    port: 9091

spring:
    application:
        name: ace-activiti
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: activiti
        url: jdbc:mysql://${MYSQL_HOST:10.99.10.104}:${MYSQL_PORT:3306}/activiti?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.104}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
        host: ${RABBIT_MQ_HOST:10.99.10.104}
        port: ${RABBIT_MQ_PORT:5672}
        username: rabbitadmin
        password: 123456
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.bwzcpt.security.crm
    title: ace-activiti
    version: 1.0.0.SNAPSHOT
    description: 业务服务
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-activiti
    secret: 123456
    token-header: client-token

mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper