logging:
    level:
#        tk.mybatis: DEBUG
        com.bwzcpt.security.crm: DEBUG
server:
    port: 8767

spring:
    application:
        name: ace-admin
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null