logging:
    level:
#        tk.mybatis: DEBUG
        com.github.wxiaoqi.security.device: DEBUG
server:
    port: 8768

https:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-password: 123456
        key-store-password: 123456
        keyStoreType: PKCS12
        keyAlias: tomcat

spring:
    application:
        name: ace-device
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: device
        url: jdbc:mysql://10.10.11.81:3306/ag_device?useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: ${REDIS_HOST:10.10.11.81}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
        host: 10.10.11.81
        port: 5672
        username: rabbitadmin
        password: 123456
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"


#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.device
    title: ace-device
    version: 1.0.0.SNAPSHOT
    description: 设备数据服务
    contact:
        name: device

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-device
    secret: 123566
    token-header: client-token