#logging:
#  file: ./ace-gate.log

spring:
    application:
        name: ace-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.103}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
        host: ${RABBIT_MQ_HOST:10.99.10.103}
        port:  ${RABBIT_MQ_PORT:5672}
        username: rabbitadmin
        password: 123456
    zipkin:
      enabled: true
    sleuth:
      sampler:
        percentage: 1
    http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
    #data:
    #  elasticsearch:
    #    cluster-name: #默认即为 elasticsearch
    #    cluster-nodes: 10.10.10.81:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode

server:
    port: 9806 #启动端口
    tomcat:
        max-threads: 500 # Maximum amount of worker threads.
        min-spare-threads: 50 # Minimum amount of worker threads

gate:
  # 开发不进行权限校验的路径
  ignore:
    startWith: /static,/auth/oauth/,/admin/v2/api-docs,/dict/v2/api-docs,/auth/v2/api-docs,/dict/dictValue/type/comm_sex,/admin/v1/captcha,/admin/user/findPassword,/admin/code,/crm/xmglJbxx/download,/crm/exportExcel,/crm/managerBox,/crm/wechat,/crm/callCenter,/admin/sysSet/getLoadContent,/admin/scanCode/loopLogin,/admin/rabbit/,/admin/scanCode/scanLogin,/rabbitmq/rabbit/

auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 5 #1天
  client:
    token-header: client-token
    id: ace-gate  #不填则默认读取spring.application.name
    secret: 123456

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.gate
    title: ace-gate
    version: 1.0.0.SNAPSHOT
    description: 网关服务
    contact:
        name: gate


zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: REDIS #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 200
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
#          strategy: SEMAPHORE

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
