logging:
    level:
#        tk.mybatis: DEBUG
        com.bwzcpt.security.rabbit: DEBUG
server:
    port: 8711

spring:
    application:
        name: ace-rabbitmq
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: crm
        url: jdbc:mysql://rm-2ze49f7ouzmbv7y01.mysql.rds.aliyuncs.com:3306/bw_crm?useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: bw_zhywxt
        password: Bw_1qaz2wsx
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.103}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
#        host: ${RABBIT_MQ_HOST:10.99.10.103}
#        port:  ${RABBIT_MQ_PORT:5672}
        addresses: ${RABBITMQ_ADDRESS:10.99.10.103:5672}
        username: rabbitadmin
        password: 123456
        #  消息发送到交换机确认机制,是否确认回调
        publisher-confirms: true
        publisher-returns: true
        template:
          retry:
            #开启rabbitmq的生产端{template}重试机制,默认是false,默认重试3次
            enabled: true
          mandatory: false
        listener:
          simple:
            retry:
              #开启rabbitmq的消费者{listener}重试机制
              enabled: true
            #消费端采用手动应答
            acknowledge-mode: manual
        cache:
          connection:
            mode: channel
          channel:
            size: 10
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
     cloud:
        inetutils:
            preferred-networks: ${NETWORKS_WD:10.255.0}
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    
# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"


#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE


# 配置swagger
swagger:
    enabled: true
    base-package: com.bwzcpt.security.rabbit
    title: ace-rabbitmq
    version: 1.0.0.SNAPSHOT
    description: MQ服务
    contact:
        name: rabbitmq

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-rabbitmq
    secret: 123456
    token-header: client-token
    
mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper