logging:
    level:
#        tk.mybatis: DEBUG
        com.bwzcpt.security.rabbit: DEBUG
server:
    port: 9809

spring:
    application:
        name: ace-rabbitmq
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: crm
        url: jdbc:mysql://10.10.10.81:3306/bw_crm?useUnicode=true&characterEncoding=UTF8&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: ${REDIS_HOST:10.10.10.81}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    rabbitmq:
       host: 10.10.10.81
       port: 5672
       username: rabbitadmin
       password: 123456
       #  消息发送到交换机确认机制,是否确认回调
       publisher-confirms: true
       publisher-returns: true
       template:
         retry:
           #开启rabbitmq的生产端{template}重试机制,默认是false,默认重试3次
           enabled: true
         mandatory: false
       listener:
         simple:
           prefetch: 1
           acknowledge-mode: auto
    zipkin:
        enabled: true
    sleuth:
        sampler:
            percentage: 1
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    
# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"


#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE


# 配置swagger
swagger:
    enabled: true
    base-package: com.bwzcpt.security.rabbit
    title: ace-rabbitmq
    version: 1.0.0.SNAPSHOT
    description: MQ服务
    contact:
        name: rabbitmq

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-rabbitmq
    secret: 123456
    token-header: client-token
    
mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper

sms:
  dingtalk:
    webhook: https://oapi.dingtalk.com/robot/send?access_token=f2b6e20ff209ab2836119241441e9809d383c93978f5bc9e15b1fe0affe00cd1
  aliyun:
    accessKey: LTAIwSKuYFlrGjf0
    secretKey: XD5O8w3Dff7pWkGoakiSPlKfFSJBfb
    channels:
      #登录验证
      loginCodeChannel: SMS_149990052
      #找回密码
      findPasswordChannel: SMS_149990049
      #设备采购
      deviceProcurementChannel: SMS_152505274
      #总号段审批
      totalSegmentApprovalChannel: SMS_152505268
      #子号段审批
      subSegmentApprovalChannel: SMS_152505270
      #项目申报
      projectApplicationChannel: SMS_152505272
      #新产品申请
      newProductApplicationChannel: SMS_152510147
      #符合性验证
      complianceVerficationChannel: SMS_152510148
      #问题工单
      problemSheetChannel: SMS_152505275
      #投诉工单
      complaintSheetChannel: SMS_152505276
      #安全码管理
      securityCodeManagementChannel: SMS_152510149
      #培训管理
      trainingManagementChannel: SMS_152510150
      #月报管理
      monthlyReportManagementChannel: SMS_152505277
      #服务派工
      serviceWorkerChannel: SMS_152505278
      #账号添加
      addAccountChannel: SMS_152510152