logging:
    level:
#        tk.mybatis: DEBUG
        com.github.wxiaoqi.oss: DEBUG
server:
    port: 9991

spring:
    profiles:
      active: dev
    application:
        name: ace-tool
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.104}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
    http:
      multipart:
        max-file-size: 10Mb
        max-request-size: 10Mb
# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"


#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.oss
    title: ace-gate
    version: 1.0.0.SNAPSHOT
    description: sssssssssqqqqqq
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-tool
    secret: 123456
    token-header: client-token
    
mapper:
  mappers: com.github.wxiaoqi.security.common.mapper.CommonMapper

# 具体看类:CloudStorageConfig
oss:
  type: 1 # 类型 1：七牛  2：阿里云  3：腾讯云
  qiniuDomain: http://ofsc32t59.bkt.clouddn.com
  qiniuPrefix: oss
  qiniuAccessKey: FAvmtRaY_yUC6Taj0b3sM8k2Wa6BDOUBy3KVBdT_
  qiniuSecretKey: a0P8OtyJv7weu7_z9YtXzplfcIzKtcHR2da_qemk
  qiniuBucketName: image

search:
  lucence:
    path: ./lucence/file