server:
  port: 8082

spring:
  application:
    name: ace-workflow
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  datasource:
    name: workflow
    url: jdbc:mysql://rm-2ze49f7ouzmbv7y01.mysql.rds.aliyuncs.com:3306/ag_workflow?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: bw_zhywxt
    password: Bw_1qaz2wsx
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  redis:
        database: 1
        host: ${REDIS_HOST:10.99.10.103}
        port: ${REDIS_PORT:6379}
        pool:
            max-active: 20
  cloud:
        inetutils:
            preferred-networks: ${NETWORKS_WD:10.255.0}

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


hystrix:
  threadpool:
    default:
            coreSize: 1000
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.wf
    title: ace-workflow
    version: 1.0.0.SNAPSHOT
    description: 工作流服务
    contact:
        name: workflow


# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: ace-workflow
    secret: 123456
    token-header: client-token

logging:
  level:
    com.github.wxiaoqi.security.wf: debug
#    org.activiti: debug
#    org.framework: debug